version = 1

# https://kodiakhq.com/docs/recipes#configuring-automerge-by-upgrade-type
[merge.automerge_dependencies]
versions = ["major", "minor", "patch"]
usernames = ["dependabot"]

# if using `update.always`, add dependabot to `update.ignore_usernames` to allow
# dependabot to update and close stale dependency upgrades.
[update]
ignored_usernames = ["dependabot"]
